services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vpwa-frontend
    ports:
      - "9000:9000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://backend:3333
#     depends_on:
#       - backend
#
#   backend:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     container_name: vpwa-backend
#     ports:
#       - "3333:3333"
#     volumes:
#       - ./backend:/app
#       - /app/node_modules
#     depends_on:
#       - db
#
#   db:
#     image: postgres:15
#     container_name: vpwa-db
#     restart: always
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_USER: vpwa_user
#       POSTGRES_PASSWORD: vpwa_pass
#       POSTGRES_DB: vpwa_db
#     volumes:
#       - db_data:/var/lib/postgresql/data
#
# volumes:
#   db_data:
